#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# Generates a .env file with random credentials and Kibana encryption keys.
# If Tailscale is present, the Tailscale IPv4 address is used as the bind
# address so the endpoint can ship events and you can reach Kibana privately.
#
#   ./scripts/bootstrap-env.sh            # auto-detect Tailscale, else loopback
#   BIND_ADDR=100.1.2.3 ./scripts/bootstrap-env.sh
#   FORCE=1 ./scripts/bootstrap-env.sh    # overwrite an existing .env
# ---------------------------------------------------------------------------
set -euo pipefail

cd "$(dirname "$0")/.."

if [[ -f .env && "${FORCE:-0}" != "1" ]]; then
  echo ".env already exists. Re-run with FORCE=1 to regenerate (this changes all passwords)." >&2
  exit 1
fi

rand() { LC_ALL=C tr -dc 'A-Za-z0-9' </dev/urandom | head -c "${1:-32}"; }

BIND_ADDR="${BIND_ADDR:-}"
if [[ -z "$BIND_ADDR" ]] && command -v tailscale >/dev/null 2>&1; then
  BIND_ADDR="$(tailscale ip -4 2>/dev/null | head -n 1 || true)"
fi
BIND_ADDR="${BIND_ADDR:-127.0.0.1}"

STACK_VERSION="${STACK_VERSION:-9.5.5}"
ES_HEAP="${ES_HEAP:-1g}"
LICENSE="${LICENSE:-basic}"

umask 077
cat > .env <<EOF
# Generated by scripts/bootstrap-env.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# DO NOT COMMIT THIS FILE.

STACK_VERSION=${STACK_VERSION}
LICENSE=${LICENSE}
ES_HEAP=${ES_HEAP}

ELASTIC_PASSWORD=$(rand 28)
KIBANA_SYSTEM_PASSWORD=$(rand 28)
BEATS_PASSWORD=$(rand 28)
ANALYST_PASSWORD=$(rand 28)

KIBANA_ENCRYPTION_KEY=$(rand 48)
REPORTING_ENCRYPTION_KEY=$(rand 48)
SECURITY_ENCRYPTION_KEY=$(rand 48)

ES_BIND_ADDR=${BIND_ADDR}
KIBANA_BIND_ADDR=${BIND_ADDR}
KIBANA_PUBLIC_URL=http://${BIND_ADDR}:5601
EOF

chmod 600 .env

echo "Wrote .env (mode 600)."
echo "Bind address: ${BIND_ADDR}"
if [[ "$BIND_ADDR" == "127.0.0.1" ]]; then
  echo
  echo "NOTE: bound to loopback only. The endpoint cannot ship events yet."
  echo "      Set ES_BIND_ADDR / KIBANA_BIND_ADDR to the soc-server Tailscale IP"
  echo "      (tailscale ip -4) and run 'make up' again."
fi
echo
echo "Show credentials later with: make passwords"
